apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: online-order
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/part-of: online-order-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
