apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: online-order
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/part-of: online-order-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sqlserver
  ports:
    - name: sql
      port: 1433
      targetPort: sql
