apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-order
  namespace: online-order
  labels:
    app.kubernetes.io/part-of: online-order-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: online-order.local
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  name: http
