apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - sqlserver/pvc.yaml
  - sqlserver/deployment.yaml
  - sqlserver/service.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - seq/deployment.yaml
  - seq/service.yaml
  - productservice/deployment.yaml
  - productservice/service.yaml
  - orderservice/deployment.yaml
  - orderservice/service.yaml
  - inventoryservice/deployment.yaml
  - inventoryservice/service.yaml
  - authservice/deployment.yaml
  - authservice/service.yaml
  - apigateway/deployment.yaml
  - apigateway/service.yaml
  - ingress.yaml
