apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: online-order
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: online-order-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
