apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: online-order
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: online-order-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
