apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: online-order
  labels: { app.kubernetes.io/name: authservice, app.kubernetes.io/part-of: online-order-system }
spec:
  selector: { app.kubernetes.io/name: authservice }
  ports: [{ name: http, port: 80, targetPort: http }]
