apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: online-order
  labels: { app.kubernetes.io/name: apigateway, app.kubernetes.io/part-of: online-order-system }
spec:
  selector: { app.kubernetes.io/name: apigateway }
  ports: [{ name: http, port: 80, targetPort: http }]
